#%%writefile Dockerfile
#FROM python:3.9-slim

#WORKDIR /app

#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

#COPY notebooks/ ./app

#EXPOSE 8000

#CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]

FROM python:3.10-slim

WORKDIR /app

# Install poetry
RUN pip install --no-cache-dir poetry

# Copy only pyproject.toml and poetry.lock (if you have it)
COPY pyproject.toml poetry.lock* /app/

# Install dependencies
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi --no-root

# Copy the rest of the code
COPY . .

EXPOSE 8000

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]